version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: foodlogs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  backend:
    build: ./back
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/foodlogs

volumes:
  postgres_data:
